FROM ubuntu:22.04

RUN apt-get update \
  && env DEBIAN_FRONTEND=noninteractive TZ=Europe/Zurich \
  apt-get -yqq install --no-install-recommends build-essential cmake mpich \
  && rm -Rf /var/lib/apt/lists/*
