include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - cleanup

cleanup rfm:
  extends: .baremetal-runner-daint-gh200
  stage: cleanup
  script:
    - cd $SCRATCH
    - |
      for dir in $(find . -maxdepth 1 -name "rfm*" -ctime +1 -type d) ; do
          echo "Creating tar archive of $dir"
          tar -czf "$dir.tar.gz" "$dir"
          rm -Rf "$dir"
      done
  variables:
    SLURM_PARTITION: xfer
    SLURM_TIMELIMIT: '02:00:00'
