include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - cleanup

cleanup rfm:
  extends: .baremetal-runner-daint-gh200
  stage: cleanup
  script:
    - |
      pushd $SCRATCH
      for dir in $(find . -maxdepth 1 -name "rfm_mlperf*" -ctime +1 -type d) ; do
          echo "Cleaning up mlperf directory at $dir"
          rm -Rf "$dir"
      done
      for dir in $(find . -maxdepth 1 -name "rfm-*" -ctime +1 -type d) ; do
          echo "Creating tar archive of $dir"
          tar -czf "$dir.tar.gz" "$dir"
          rm -Rf "$dir"
      done
      popd
    - git clone https://github.com/bcumming/spack-cache-util
    - cd spack-cache-util
    - export PATH=/capstor/scratch/cscs/anfink/shared:$PATH
    - ./signatures.sh $SCRATCH/uenv-cache/user-environment/build_cache
    - ./signatures.sh $SCRATCH/uenv-cache/user-environment/build_cache
    - quota
  variables:
    SLURM_PARTITION: xfer
    SLURM_TIMELIMIT: '02:00:00'
