include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - cleanup

cleanup rfm:
  extends: .baremetal-runner-daint-gh200
  stage: cleanup
  script:
    - |
      for dir in $(find $SCRATCH -maxdepth 1 -name "rfm*" -type d ; do
          tar -czf "$dir" "$dir.tar.gz"
          rm -Rf "$dir"
      done
  variables:
    SLURM_PARTITION: xfer
    SLURM_TIMELIMIT: '02:00:00'
