include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - cleanup

cleanup rfm:
  extends: .baremetal-runner-daint-gh200
  timeout: 40h
  stage: cleanup
  script:
    - |
      pushd $SCRATCH
      for dir in $(find . -maxdepth 1 -name "rfm_mlperf*" -ctime +1 -type d) ; do
          echo "Cleaning up mlperf directory at $dir"
          rm -Rf "$dir"
      done
      for dir in $(find . -maxdepth 1 -name "rfm-*" -ctime +1 -type d) ; do
          echo "Creating tar archive of $dir"
          tar --exclude="checkpoints/iter*" -czf "$dir.tar.gz" "$dir"
          rm -Rf "$dir"
      done
      pushd /iopsstor/scratch/cscs/$(id -un)
      for dir in $(find . -maxdepth 1 -name "rfm_mlperf*" -ctime +1 -type d) ; do
          echo "Cleaning up mlperf directory at $dir"
          rm -Rf "$dir"
      done
      for dir in $(find . -maxdepth 1 -name "rfm-*" -ctime +1 -type d) ; do
          echo "Creating tar archive of $dir"
          tar --exclude="checkpoints/iter*" -czf "$dir.tar.gz" "$dir"
          rm -Rf "$dir"
      done
    - quota
  variables:
    SLURM_PARTITION: xfer
    SLURM_TIMELIMIT: '16:00:00'

cleanup spack-cache:
  extends: .baremetal-runner-daint-gh200
  stage: cleanup
  script:
    - git clone https://github.com/bcumming/spack-cache-util
    - cd spack-cache-util
    - export PATH=/capstor/scratch/cscs/anfink/shared:$PATH
    - ./signatures.sh $SCRATCH/uenv-cache/user-environment/build_cache
    - ./signatures.sh $SCRATCH/uenv-cache/user-environment/build_cache
    - find $SCRATCH/firecrest/ -type f -atime +40 | wc -l
    - |
      if [[ $(date '+%u') -eq 6 ]] ; then
        set -x
        echo "Cleaning up empty directories and broken symlinks"
        find $SCRATCH -mindepth 1 -maxdepth 1 -type d -ctime +30 -empty -delete
        find $SCRATCH -mindepth 1 -maxdepth 1 -type d -ctime +30 -exec bash -c 'if [[ $(find {} -type f | wc -l) -eq 0 ]] ; then echo Deleting directory {} ; rm -Rf {} ; else touch {} ; fi' \;
        find $SCRATCH/firecrest -mindepth 1 -maxdepth 1 -type d -empty -delete
        find $SCRATCH/firecrest -mindepth 1 -maxdepth 1 -type d -ctime +30 -exec bash -c 'if [[ $(find {} -type f | wc -l) -eq 0 ]] ; then echo Deleting directory {} ; rm -Rf {} ; else touch {} ; fi' \;
        find $SCRATCH/gitlab-runner/cache -mindepth 2 -maxdepth 2 -type d -empty -delete
        find $SCRATCH/gitlab-runner/cache -mindepth 2 -maxdepth 2 -type d -ctime +30 -exec bash -c 'if [[ $(find {} -type f | wc -l) -eq 0 ]] ; then echo Deleting directory {} ; rm -Rf {} ; else touch {} ; fi' \;
        find $SCRATCH/gitlab-runner/f7t -mindepth 2 -maxdepth 2 -type d -empty -delete
        find $SCRATCH/gitlab-runner/f7t -mindepth 2 -maxdepth 2 -type d -ctime +30 -exec bash -c 'if [[ $(find {} -type f | wc -l) -eq 0 ]] ; then echo Deleting directory {} ; rm -Rf {} ; else touch {} ; fi' \;
        set +x
      fi
    - quota
  variables:
    SLURM_PARTITION: xfer
    SLURM_TIMELIMIT: '02:00:00'

cleanup ciext logs:
  extends: .baremetal-runner-daint-gh200
  stage: cleanup
  script:
    # get all log files older than 1 day, and pack into a tar-archive
    # delete log files and only keep tar archive in case inspection is needed at a later time
    # do not delete tar archives and leave this to the cleanup policy of scratch
    - cd $SCRATCH/ciext_logs
    - TIMESTAMP=$(date +"%s")
    - mkdir -p $TIMESTAMP
    - find . -mindepth 1 -maxdepth 1 -mtime +1 -name "*.log" -exec mv --target $TIMESTAMP {} +
    - tar -cvzf $TIMESTAMP.tar.gz $TIMESTAMP
    - rm -Rf $TIMESTAMP
  variables:
    F7T_CLIENT_ID: $F7T_ANFINK_CLIENT_ID
    F7T_CLIENT_SECRET: $F7T_ANFINK_CLIENT_SECRET
    SLURM_PARTITION: xfer
    SLURM_TIMELIMIT: '00:30:00'
