on: [push]

permissions:
  id-token: write # This is required for requesting the JWT

jobs:
  job-on-compute-node:
    runs-on: ubuntu-latest
    name: A job to run on the compute node
    steps:
      - name: Inspect JWT
        run: |
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run on compute node
        uses: finkandreas/actions-playground@main
        id: firecrest
        with:
          script: |
            set -x
            echo "This is my first line and it is running on hostname=$(hostname)"
            ls -alh $SCRATCH
            hostname > some_new_file
            date
            env
            ls -alh
            pwd
            echo 'some github step summary with `markdown` support' >> $GITHUB_STEP_SUMMARY
            echo "test_new_env=test_value" >> "$GITHUB_ENV"
            curl -v -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://cicd-ext-mw.cscs.ch" > test.jwt
          firecrest_client_id: ${{ secrets.FIRECREST_CLIENT_ID }}
          firecrest_client_secret: ${{ secrets.FIRECREST_CLIENT_SECRET }}
        env:
          SLURM_ACCOUNT: csstaff
          SLURM_JOB_NUM_NODES: 1
          SLURM_PARTITION: debug
      - name: Inspect workspace
        run: |
          ls -alh
          pwd
          env
          cat some_new_file
